"use client";
import {useMemo,useState} from "react";
import {BadgeCheck,BedSingle,Clock,MailCheck,MessageCircle,Phone,Search,XCircle} from "lucide-react";
type Booking={id:number;reference:string;hostelName:string;fullName:string;phone:string;email:string|null;roomType:string;gender:string;moveInDate:string;message:string|null;status:string;createdAt:string};
export default function ManagerDashboard({initialBookings}:{initialBookings:Booking[]}){
 const[items,setItems]=useState(initialBookings),[filter,setFilter]=useState("all"),[query,setQuery]=useState(""),[notice,setNotice]=useState("");
 const shown=useMemo(()=>items.filter(x=>(filter==="all"||x.status===filter)&&(`${x.fullName} ${x.phone} ${x.reference}`.toLowerCase().includes(query.toLowerCase()))),[items,filter,query]);
 const update=async(id:number,status:string)=>{setNotice("");const r=await fetch("/api/manager/bookings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});const d=await r.json();if(r.ok){setItems(a=>a.map(x=>x.id===id?{...x,status}:x));setNotice(d.emailSent?"Status updated and the student was notified by email.":d.emailSkipped?"Status updated. No student email was required or available.":"Status updated, but the email could not be delivered.")}else setNotice(d.error||"The request could not be updated.")};
 const whatsapp=(x:Booking)=>{const phone=x.phone.replace(/\D/g,"").replace(/^0/,"256");const message=`Hello ${x.fullName}, your ${x.roomType} room request (${x.reference}) at ${x.hostelName} has been confirmed. You may now proceed with payment. Please contact the hostel manager to verify the official payment details before sending money.`;return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`};
 const pending=items.filter(x=>x.status==="pending").length,confirmed=items.filter(x=>x.status==="confirmed").length,rejected=items.filter(x=>x.status==="rejected").length;
 return <><section className="manager-stats"><article><Clock/><span><b>{pending}</b>Pending requests</span></article><article><BadgeCheck/><span><b>{confirmed}</b>Confirmed</span></article><article><XCircle/><span><b>{rejected}</b>Rejected</span></article><article><BedSingle/><span><b>{items.length}</b>Total requests</span></article></section><section className="sms-tester"><div><span>EMAIL ACTIVE</span><h2><MailCheck size={20}/>Automatic email notifications</h2><p>You receive new-request alerts. Students with an email address are notified when you confirm or reject their request.</p></div>{notice&&<p className="sms-result">{notice}</p>}</section><section className="manager-panel"><div className="manager-tools"><div className="manager-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, phone or reference"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All requests</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="rejected">Rejected</option></select></div>{shown.length?<div className="request-list">{shown.map(x=><article className="request-card" key={x.id}><div className="request-top"><div><span className={`status ${x.status}`}>{x.status}</span><small>{x.reference}</small><h2>{x.fullName}</h2><p>{x.gender} · {x.roomType} room · Move in {x.moveInDate}</p></div><a className="call-student" href={`tel:${x.phone.replace(/\s/g,"")}`}><Phone size={16}/>Call {x.phone}</a></div><div className="request-details"><span><small>Hostel</small>{x.hostelName}</span><span><small>Email</small>{x.email||"Not provided"}</span><span><small>Submitted</small>{new Date(x.createdAt+"Z").toLocaleDateString("en-UG")}</span></div>{x.message&&<blockquote>{x.message}</blockquote>}<div className="request-actions"><button onClick={()=>update(x.id,"confirmed")} disabled={x.status==="confirmed"}><BadgeCheck size={16}/>Confirm room</button>{x.status==="confirmed"&&<a className="notify-student" href={whatsapp(x)} target="_blank" rel="noreferrer"><MessageCircle size={16}/>Send payment notification</a>}<button className="reject" onClick={()=>update(x.id,"rejected")} disabled={x.status==="rejected"}><XCircle size={16}/>Reject</button><button className="pending-btn" onClick={()=>update(x.id,"pending")} disabled={x.status==="pending"}><Clock size={16}/>Mark pending</button></div></article>)}</div>:<div className="manager-empty"><Search size={32}/><h2>No booking requests found</h2><p>New student requests will appear here automatically.</p></div>}</section></>
}
